FROM ubuntu:14.04
MAINTAINER harlo <harlo.holmes@gmail.com>

# UPDATE
RUN apt-get update
RUN apt-get install -yq wget zip unzip openssl git python make openssh-server

# ADD OUR PRIMARY USER
RUN useradd -ms /bin/bash -p $(openssl passwd -1 ${USER_PWD}) ${USER}
RUN adduser ${USER} sudo

# ADD FILES GALORE
ADD make /home/${USER}/
RUN mkdir /home/${USER}/.ssh

# SET UP USER STUFF
RUN echo "${USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN chown -R ${USER}:${USER} /home/${USER}
USER ${USER}
ENV HOME /home/${USER}
ENV PACKAGE_NAME ${SUPER_PACKAGE}
ENV ANNEX_LOCAL ${ANNEX_LOCAL}
WORKDIR /home/${USER}

CMD ["/bin/bash", "./install.sh"]

EXPOSE ${MAIN_PORT}