FROM ${ANNEX_BUILD}
MAINTAINER harlo <harlo.holmes@gmail.com>

RUN sudo apt-get update

ADD make /home/${USER}
RUN sudo chown -R ${USER}:${USER} /home/${USER}/${SUPER_PACKAGE}

CMD ["/bin/bash", "./install.sh"]

EXPOSE ${MAIN_PORT} ${ANNEX_PORTS}