FROM ubuntu:14.04
MAINTAINER harlo <harlo.holmes@gmail.com>

# ADD OUR PRIMARY USER
RUN useradd -ms /bin/bash ${ANNEX_USER}

# UPDATE
#RUN apt-get update -qq
#RUN apt-get install -yq wget nginx zip unzip openjdk-7-jre-headless

# ADD FILES GALORE
ADD . /home/${ANNEX_USER}/${SUPER_PACKAGE}
RUN chown -R ${ANNEX_USER}:${ANNEX_USER} /home/${ANNEX_USER}
USER ${ANNEX_USER}
ENV HOME /home/${ANNEX_USER}
WORKDIR /home/${ANNEX_USER}/${SUPER_PACKAGE}

EXPOSE 22 443