FROM ubuntu:14.04
MAINTAINER harlo <harlo.holmes@gmail.com>

# UPDATE
RUN apt-get update
RUN apt-get install -yq wget zip unzip openjdk-7-jre-headless openssl git python make openssh-server

# ADD OUR PRIMARY USER
RUN useradd -ms /bin/bash -p $(openssl passwd -1 ${ANNEX_USER_PWD}) ${ANNEX_USER}
RUN adduser ${ANNEX_USER} sudo

# ADD FILES GALORE
ADD make /home/${ANNEX_USER}/
RUN mkdir /home/${ANNEX_USER}/.ssh

# SET UP USER STUFF
RUN echo "${ANNEX_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN chown -R ${ANNEX_USER}:${ANNEX_USER} /home/${ANNEX_USER}
USER ${ANNEX_USER}
ENV HOME /home/${ANNEX_USER}
WORKDIR /home/${ANNEX_USER}

CMD ["/bin/bash", "./install.sh"]

EXPOSE 9200 ${EXTRA_PORTS}